{
 "title": "Kubernetes / System / PVC",
 "description": "Monitors all persistent volumes that exists within a Kubernetes cluster. Prometheus is used as datasource. ",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "k8s_namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 10 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}[1d], 10 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 20 Days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}[1d], 20 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} )) >= (${warning_threshold} / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVC Full in days - Based on daily usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_available_bytes{namespace=~\".*\"})/1024/1024/1024 and (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\".*\"}[1d], 10 * 24 * 60 * 60) < 0) ",
     "legendFormat": "10d {{namespace}} ({{persistentvolumeclaim}})"
    },
    {
     "expr": "(kubelet_volume_stats_available_bytes{namespace=~\".*\"})/1024/1024/1024 and (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\".*\"}[1d], 20 * 24 * 60 * 60) < 0) ",
     "legendFormat": "20d {{namespace}} ({{persistentvolumeclaim}})"
    },
    {
     "expr": "(kubelet_volume_stats_available_bytes{namespace=~\".*\"})/1024/1024/1024 and (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\".*\"}[1d], 5 * 24 * 60 * 60) < 0) ",
     "legendFormat": "5d {{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=~\"${k8s_namespace}\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim,namespace) + sum(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Lost)\"}) by (persistentvolumeclaim,namespace)"
    },
    {
     "expr": "sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} * 100)"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  },
  { "title": "Graphical usage data ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hourly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1h])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Usage Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1w])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}