#!/bin/bash
#1-store
source $HOME/oci-manage
if [ -z "${CRYPTOKEN}" ]; then
    echo "CRYPTOKEN is empty: $CRYPTOKEN"
    exit -1
fi

PWD=`pwd`
cd $HOME
tar --exclude .kube/cache -cvJf _sensitive_datas/_sensitive_datas.tar.xz oci-manage-config.sh oci.json .mc .bashrc .ssh .kube .oci .azure .docker pki wg/database.csv production iptables/rules.v4
#2-encrypt
openssl aes-256-cbc -base64 -md sha256 -pass pass:"$CRYPTOKEN" -in _sensitive_datas/_sensitive_datas.tar.xz -out _sensitive_datas/_sensitive_datas.tar.xz.enc 2>/dev/null
#3-delete 
rm _sensitive_datas/_sensitive_datas.tar.xz
cd $PWD
echo "CRYPTED with 'openssl aes-256-cbc -base64 -md sha256 -pass pass:\"$CRYPTOKEN\"'"

# Check if the sensitive datas _sensitive_datas/_sensitive_datas.tar.xz.enc was not encrypted with an empty password
# try to decrypt with the empty password
openssl aes-256-cbc -a -d -md sha256 -pass pass:"" -in _sensitive_datas/_sensitive_datas.tar.xz.enc -out - 2>/dev/null | tar -tvJ > /dev/null 2> /dev/null
if [ $? -eq 0 ]; then
    echo ""
    echo "ERROR"
    echo "The sensitive datas _sensitive_datas/_sensitive_datas.tar.xz.enc was encrypted with an empty password"
    rm $HOME/_sensitive_datas/_sensitive_datas.tar.xz.enc
    exit -1
fi