#!/bin/bash
. ~/oci-manage
cluster_ping6_host_from_members 2606:4700:4700::1111
cluster_ping_cross_from_members
cluster_ping_host_from_members 10.254.0.4
cluster_ping_host_from_members 192.168.168.109 
cluster_ping_host_from_members 192.168.2.8
